FROM frolvlad/alpine-miniconda3

COPY requirements.txt .

RUN apk add musl-dev linux-headers g++
RUN pip install -r requirements.txt

ADD utils ./
COPY api.py .
COPY model.py .

EXPOSE 8050

RUN mkdir logs
RUN mkdir models

RUN python model.py